### ISSUE TITLE
Settings don't work 

### ISSUE THREAD

**Issue by catsmoker** [Schwartzblat/WhatsAppPatcher#76]
When you tap on settings the app starts to glitch and it's closing it self

**Comment by edgarz123** [comment]
I have the same problem

**Comment by KurtzPT** [comment]
Tried out my old patched version  (2.23.25.83) + patched a newer version (2.24.1.78) on a brand new phone and I'm having this issue. Settings will crash the app everytime.

Funny enough my old phone with the old patched version (2.23.25.83) does not have this issue, but the instalation was done 1+ month ago.

**Comment by jeverling** [comment]
I just downloaded the latest stable version from https://www.whatsapp.com/android/, patched it and it seems to work fine (Google auth for backup doesn't work, but that's another issue).
Version should be 2.24.2.74.

**Comment by Schwartzblat** [comment]
Let me know if it solved.

**Comment by jeverling** [comment]
Well the settings work with the latest stable version  2.24.2.74.
However, what doesn't work is authenticating your number, it throws an error "There is something wrong with your version of WhatsApp". Also authenticating with Google doesn't work.
If you install over an already authenticated app and don't need Google Drive backup the rest works great as far as I can tell.

Maybe it would be a good idea to patch a stable version in CI, I don't know if they do expire as well, but probably much less frequently than the beta versions.

**Comment by starsunyzl** [comment]
> Tried out my old patched version (2.23.25.83) + patched a newer version (2.24.1.78) on a brand new phone and I'm having this issue. Settings will crash the app everytime.
> 
> Funny enough my old phone with the old patched version (2.23.25.83) does not have this issue, but the instalation was done 1+ month ago.
> 
> Crashlog:
> 
> ```
> java.lang.SecurityException: Access denied. Caller is not trusted: TrustedCallerInfo{isTrusted=false, uid=10383, signature=XQgmS0Tg5T-8zHC08BZHTMbFq1w, packageNames=[com.whatsapp]}
>  at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
>  at android.os.Parcel.createException(Parcel.java:3053)
>  at android.os.Parcel.readException(Parcel.java:3036)
>  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
>  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
>  at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
>  at android.content.ContentResolver.query(ContentResolver.java:1229)
>  at android.content.ContentResolver.query(ContentResolver.java:1161)
>  at android.content.ContentResolver.query(ContentResolver.java:1117)
>  at X.3w3.run(:746)
>  at X.10c.run(:1)
>  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
>  at X.1ru.run(:498)
>  at java.lang.Thread.run(Thread.java:1012)
> ```



> Tried out my old patched version (2.23.25.83) + patched a newer version (2.24.1.78) on a brand new phone and I'm having this issue. Settings will crash the app everytime.
> 
> Funny enough my old phone with the old patched version (2.23.25.83) does not have this issue, but the instalation was done 1+ month ago.
> 
> Crashlog:
> 
> ```
> java.lang.SecurityException: Access denied. Caller is not trusted: TrustedCallerInfo{isTrusted=false, uid=10383, signature=XQgmS0Tg5T-8zHC08BZHTMbFq1w, packageNames=[com.whatsapp]}
>  at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
>  at android.os.Parcel.createException(Parcel.java:3053)
>  at android.os.Parcel.readException(Parcel.java:3036)
>  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
>  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
>  at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
>  at android.content.ContentResolver.query(ContentResolver.java:1229)
>  at android.content.ContentResolver.query(ContentResolver.java:1161)
>  at android.content.ContentResolver.query(ContentResolver.java:1117)
>  at X.3w3.run(:746)
>  at X.10c.run(:1)
>  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
>  at X.1ru.run(:498)
>  at java.lang.Thread.run(Thread.java:1012)
> ```

Your old phone might not have the com.facebook.appmanager package, you can confirm this by `adb shell pm list packages` command.

The reason for this error is because WhatsApp communicates with com.facebook.appmanager, which verifies whether WhatsApp is trusted. If it's not trusted(for example, it has been patched), WhatsApp will crash.

**Comment by Schwartzblat** [comment]
Not relevant, move to the new infrastructure :)
